### PR TITLE
[#10] Rename classes and pages to represent functionality

### PR DESCRIPTION
**Pull request by americanyorkie**
Refactoring class/page names to more clearly map to functionality.
Changes include:
suggestion.html -> status.html
custom.html -> histogram.html
tokens.html -> users.html
java/SecurityConfiguration -> ApplicationConfiguration
security.properties -> application.properties

Make sure you have checked all steps below.

### GitHub Issue
Fixes #<issue>

### Checklist:

- [x] This pull request updates the documentation
- [x] This pull request changes the code
- [x] Title of the PR is of format (example) : `[#25] Add Pull Request Template`, where `[#25] is the GitHub issue number`

### What is the purpose of this pull request?
This pull request renames some classes and filenames to more closely reflect the functionality of that object.

### How was this change validated?
Verified through the execution of tests on all currently supported Hadoop distributions.

### Commit Guidelines
- [x] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by zero45** [comment]
Can you run a test instance of this and make sure everything is accessible from the Navbar?
I believe `navbar.html` and other HTML pages need some URLs changed.

**Comment by zero45** [comment]
Hey @americanyorkie, were you still interested in this? I'd like to get this in for the next release. I think the goal will be this, #122, and #108 for version 1.5.0.

**Comment by zero45** [comment]
Hi @americanyorkie -- this has gotten too stale now and didn't make it into the 1.5.0 release. Reach out to me when you can so we can try to get it in a later release.

**Comment by pjeli** [comment]
This is too dated now and most features are in. Closing.

**Pull request closed without merging**
