### PR TITLE
[#52] Document the web API

### LINKED ISSUE #52: Document the web API
Now that we have https://nnanalytics.readthedocs.io/en/latest/ up it would be nice to document how the web API queries work and the different options available.

### PR DESCRIPTION
**Pull request by zero45**
Make sure you have checked all steps below.

### GitHub Issue
Fixes #52 

### Checklist:

- [X] This pull request updates the documentation
- [ ] This pull request changes the code
- [X] Title of the PR is of format (example) : `[#25] Add Pull Request Template`, where `[#25] is the GitHub issue number`

### What is the purpose of this pull request?
Documentation

### Commit Guidelines
- [X] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by Dee-Pac** [comment]
@zero45 

- I feel querying should be a separate folder say `How_To_Query` or `Advanced Analytics`

**Comment by Dee-Pac** [comment]
@zero45 
- In each of the subfolder, say `sets` - it would be more explanatory if we have one full example of query.

**Comment by Dee-Pac** [comment]
Apart from above comments - LGTM

**Comment by zero45** [comment]
Thanks @Dee-Pac ! Regarding the subfolders -- `set` is a parameter to the queries. Example queries can be found in `How To Query`. Is that satisfactory? The goal is for each subfolder to just explain the various options.

**Comment by Dee-Pac** [comment]
@zero45 - to your above comment, its fine. The only downside is this : 

https://nn-analytics.readthedocs.io/en/latest

- currently, `How To Query` is at the same level as `getting started`?all the sublevels such as `sets` , `filters` etc will not be ordered well on the navigation window. 
Currently - in readthedocs - `FilterOps` appears first & the ordering is all lost.

Hence a user looks at `FilterOps` first thing on the left navigation.

**Comment by zero45** [comment]
Oh interesting -- I wasn't able to see that before. Yeah we should definitely get that fixed up. I'll add directories. Thanks @Dee-Pac!

**Comment by zero45** [comment]
Okay @Dee-Pac -- I think now it should look a lot cleaner. Check here: https://nnanalytics.readthedocs.io/en/doc_web_api/

If you like it too then feel free to `Rebase and Merge` after your +1. :)
Just make sure the commit message is like the ones currently in the `git log`.

Thanks!

**Comment by Dee-Pac** [comment]
Above is result of the markdown headings within each document. If you don't want the duplication, then you may just remove `##` on the `How to build:` within each markdown file, and make it just a line. And may just underline using `_`?

**Comment by zero45** [comment]
@Dee-Pac -- I took the approach of removing `##` and just bolding the titles instead. This looks much better I think. If you like it too then I think we are ready to +1 and move along.

Thanks for your reviews thus far as well.

**Pull request merged**
