### PR TITLE
Add support for HDFS 2.10.0

### PR DESCRIPTION
**Pull request by shvachko**
- Adding option to build NNA with HDFS 2.10.0
- Fix problem with dependency on commons-io
- Add eclipse plugin

### CODE REVIEW

**Comment by shvachko** [comment]
Guess need to update supported versions in the doc.

**Comment by pjeli** [comment]
Hey Konstantin. Sorry it has been a while. Can you please re-base to the latest commit on master branch and push to your PR branch again? It turns out Travis CI (in the way I was using it) is deprecated now and so no CI was happening for NNA.

I have merged in the commons-io fix as that was affecting the entire build, so your new PR should be simpler.

Again, sorry, but at least next PR push will have CI for build.

**Comment by pjeli** [comment]
Couple things will need to be updated, can be here or as part of separate issue:
- Support versions in documentation.
- Build matrix environment variable for 2.10 : https://github.com/paypal/NNAnalytics/blob/master/.github/workflows/gradle.yml

**Comment by shvachko** [comment]
Rebased the patch. Updated gradle.yml

**Review by pjeli — APPROVED** [review]

**Comment by pjeli** [comment]
Thanks for the contribution @shvachko !

**Pull request merged**
