### PR TITLE
[#26] Add a /logout endpoint

### LINKED ISSUE #26: Add a /logout endpoint
When running with authentication enabled there is no /logout endpoint and we rely instead on users managing their own cookies and sessions.

Clearly this is not ideal as users may share computers or simple just wish to not be logged in anymore and a `/logout` REST endpoint makes total sense.

Luckily pac4j makes this pretty easy to do:
https://github.com/pac4j/spark-pac4j#6-logout-logoutfilter

In `NNAConstants.java` we also have to be sure to add `/logout` as an UNSECURED endpoint.

### PR DESCRIPTION
**Pull request by zero45**
Make sure you have checked all steps below.

### GitHub Issue
Fixes #26 

### Checklist:

- [ ] This pull request updates the documentation
- [X] This pull request changes the code
- [X] Title of the PR is of format (example) : `[#25] Add Pull Request Template`, where `[#25] is the GitHub issue number`

### Commit Guidelines
- [X] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by zero45** [comment]
I have confirmed the latest commit is working in a test instance that I maintain.
After calling `/logout`; attempting to go to any other page will trigger re-authentication.

This can be easily tested locally by modifying TestNNAnalytics.beforeClass to add `    conf.set("nna.localonly.users", "hdfs:hdfs");` and then starting the `main()` or running the gradlew execute command and logging in as "hdfs" with password "hdfs" on http://localhost:4567 and then going to http://localhost:4567/logout.

**Comment by zero45** [comment]
Hm. Seems this won't work on FireFox and Chrome though. Re-thinking now that Basic Auth needs to be removed in place of a `/login` endpoint and cookies.

**Comment by zero45** [comment]
Latest change is pretty substantial -- I'll try to break down everything here:

- Added an login.html and logout.html page.
- Made previous pages check if authentication required; will redirect to login.html if needed.
- /login and /logout endpoints created; require POST methods.
- As long as you have a valid JWT cookie you should experience no changes.
- Setting any local users now enables authentication.

This can be easily tested locally by modifying TestNNAnalytics.beforeClass to add conf.set("nna.localonly.users", "hdfs:hdfs"); and then starting the main() or running the gradlew execute command and logging in as "hdfs" with password "hdfs" on http://localhost:4567.

I have confirmed on a dev instance that this is working as intended.

**Comment by rsmcelroy** [comment]
Tested on local deployment.   Results were good.

**Comment by zero45** [comment]
Thanks @ehf. Thanks @rsmcelroy. Committing shortly.

**Pull request merged**
