### PR TITLE
[#44] Skip CI for documentation-only PRs

### LINKED ISSUE #44: Skip CI for documentation-only PRs
Running Travis on NNA is expensive, taking resources for 20-30 mins. This won't scale as we add more devs on the project. One way to alleviate the issue is to avoid running it when a PR only contains documentation changes.

Refer to this : https://github.com/google/EarlGrey/pull/383/files/3b38a5dea36a88aba42a42931e77a7c5429a1837

### PR DESCRIPTION
**Pull request by r39132**
Make sure you have checked all steps below.

### GitHub Issue
Fixes #44 

### Checklist:

- [x] This pull request updates the documentation
- [] This pull request changes the code
- [ ] Title of the PR is of format (example) : `[#25] Add Pull Request Template`, where `[#25] is the GitHub issue number`

### What is the purpose of this pull request?

This change mostly changes the build trigger logic used for Travis CI on Github

### Commit Guidelines
- [x] My commits all reference GH issues in their subject lines, and I have squashed multiple commits if they address the same issue. In addition, my commits follow the guidelines from "[How to write a good git commit message](http://chris.beams.io/posts/git-commit/)":
    1. Subject is separated from body by a blank line
    2. Subject is limited to 50 characters
    3. Subject does not end with a period
    4. Subject uses the imperative mood ("add", not "adding")
    5. Body wraps at 72 characters
    6. Body explains "what" and "why", not "how"

### CODE REVIEW

**Comment by zero45** [comment]
I want to +1 but I am a little torn on the html change requirement. HTML files are a main part of the NNA experience today so might not be able to count them out. Also, we have no HTML files for documentation -- they will all be .md files as per ReadTheDocs...

What do you think, @r39132 ?

**Comment by jhsenjaliya** [comment]
+1, let see how it works.

**Comment by r39132** [comment]
@zero45 Does travis do anything with HTML files? HTML file are pretty unstructured and thought XHTML did get some attention with the hope of enforcing a schema, are we using these? If not, what the need to run a build, test, code analysis against html?

**Comment by zero45** [comment]
We can ignore the CodeCov results here. This is just doc change. Travis does not do anything with the HTML files. Spoken offline we agreed we may need to revisit this when UI becomes a focus and we add testing for UI elements.

+1. Go ahead.

**Pull request merged**
